// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';

import type { Event, Product } from '#types/externals.ts';

export interface StoryblokBiography {
	SEO: StoryblokSEO[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Biography';
	_uid: string;
}

export interface StoryblokBiographyCopyright {
	label: string;
	title: StoryblokRichtext;
	cursorProjects?: boolean;
	circularStar?: boolean;
	component: 'BiographyCopyright';
	_uid: string;
}

export interface StoryblokBiographyHero {
	title: string;
	description: string;
	titleDescriptionAndCta?: StoryblokTitleDescriptionAndCta[];
	picturePrimary: StoryblokAsset;
	pictureSecondary: StoryblokAsset;
	component: 'BiographyHero';
	_uid: string;
}

export interface StoryblokBiographyStrangersPortraits {
	title: StoryblokRichtext;
	sections?: (StoryblokBiographyStrangersPortraitsExplanation | StoryblokBiographyStrangersPortraitsVideo)[];
	copyright?: StoryblokBiographyCopyright[];
	component: 'BiographyStrangersPortraits';
	_uid: string;
}

export interface StoryblokBiographyStrangersPortraitsExplanation {
	title: StoryblokRichtext;
	description: string;
	component: 'BiographyStrangersPortraitsExplanation';
	_uid: string;
}

export interface StoryblokBiographyStrangersPortraitsVideo {
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	thumbnail: StoryblokAsset;
	video: StoryblokAsset;
	component: 'BiographyStrangersPortraitsVideo';
	_uid: string;
}

export interface StoryblokEmail {
	label: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'asset' }>;
	component: 'Email';
	_uid: string;
}

export interface StoryblokFormError {
	title: string;
	subtitle: string;
	description: string;
	component: 'FormError';
	_uid: string;
}

export interface StoryblokForms {
	id: string;
	title: string;
	description: string;
	submitLabel: string;
	formSuccess?: StoryblokFormSuccess[];
	formError?: StoryblokFormError[];
	inputs?: (
		| StoryblokInputDate
		| StoryblokInputDatetime
		| StoryblokInputEmail
		| StoryblokInputRadios
		| StoryblokInputRadiosItem
		| StoryblokInputText
		| StoryblokInputTextarea
	)[];
	component: 'Forms';
	_uid: string;
}

export interface StoryblokFormSuccess {
	title: string;
	subtitle: string;
	description: string;
	component: 'FormSuccess';
	_uid: string;
}

export interface StoryblokHome {
	SEO: StoryblokSEO[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Home';
	_uid: string;
}

export interface StoryblokHomeHero {
	title: StoryblokRichtext;
	services?: (ISbStoryData<StoryblokProject> | string)[];
	component: 'HomeHero';
	_uid: string;
}

export interface StoryblokInputDate {
	name: string;
	label: string;
	placeholder: string;
	component: 'InputDate';
	_uid: string;
}

export interface StoryblokInputDatetime {
	name: string;
	label: string;
	placeholder: string;
	component: 'InputDatetime';
	_uid: string;
}

export interface StoryblokInputEmail {
	name: string;
	label: string;
	placeholder: string;
	component: 'InputEmail';
	_uid: string;
}

export interface StoryblokInputRadios {
	name: string;
	label: string;
	items?: StoryblokInputRadiosItem[];
	component: 'InputRadios';
	_uid: string;
}

export interface StoryblokInputRadiosItem {
	label: string;
	component: 'InputRadiosItem';
	_uid: string;
}

export interface StoryblokInputText {
	name: string;
	label: string;
	placeholder: string;
	component: 'InputText';
	_uid: string;
}

export interface StoryblokInputTextarea {
	name: string;
	label: string;
	placeholder: string;
	component: 'InputTextarea';
	_uid: string;
}

export interface StoryblokLabelLink {
	label: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	component: 'LabelLink';
	_uid: string;
}

export interface StoryblokLinks {
	SEO: StoryblokSEO[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Links';
	_uid: string;
}

export interface StoryblokLinksHero {
	title: StoryblokRichtext;
	description?: string;
	backgroundMobile: StoryblokAsset;
	backgroundDesktop: StoryblokAsset;
	component: 'LinksHero';
	_uid: string;
}

export interface StoryblokLinksMaterials {
	title?: StoryblokRichtext;
	description?: string;
	materials?: (
		| StoryblokLinksMaterialsItemProduct
		| StoryblokLinksMaterialsItemTitle
		| StoryblokLinksMaterialsItemEmpty
	)[];
	component: 'LinksMaterials';
	_uid: string;
}

export interface StoryblokLinksMaterialsItemEmpty {
	columnNumber?: string;
	rowNumber?: string;
	hide?: 'hide-mobile' | 'hide-tablet';
	component: 'LinksMaterialsItemEmpty';
	_uid: string;
}

export interface StoryblokLinksMaterialsItemProduct {
	pretitle: string;
	title: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	picture: StoryblokAsset;
	columnNumber?: string;
	rowNumber?: string;
	hide?: '' | 'hide-mobile' | 'hide-tablet';
	component: 'LinksMaterialsItemProduct';
	_uid: string;
}

export interface StoryblokLinksMaterialsItemTitle {
	title: string;
	position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
	columnNumber?: string;
	rowNumber?: string;
	hide?: 'hide-mobile' | 'hide-tablet';
	component: 'LinksMaterialsItemTitle';
	_uid: string;
}

export interface StoryblokMenu {
	title: string;
	description: string;
	navLinks?: StoryblokLabelLink[];
	component: 'Menu';
	_uid: string;
}

export interface StoryblokOtherServices {
	title?: string;
	services?: (ISbStoryData<StoryblokService> | string)[];
	component: 'OtherServices';
	_uid: string;
}

export interface StoryblokPicture {
	media: StoryblokAsset;
	component: 'Picture';
	_uid: string;
}

export interface StoryblokProject {
	SEO: StoryblokSEO[];
	informations?: StoryblokProjectInformations[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Project';
	_uid: string;
}

export interface StoryblokProjectInformations {
	name: StoryblokRichtext;
	cover: StoryblokAsset;
	coverSmall: StoryblokAsset;
	date: string;
	location: string;
	service: (ISbStoryData<StoryblokService> | string)[];
	component: 'ProjectInformations';
	_uid: string;
}

export interface StoryblokProjectsMarquee {
	title: StoryblokRichtext;
	description?: string;
	link?: StoryblokLabelLink[];
	component: 'ProjectsMarquee';
	_uid: string;
}

export interface StoryblokProjectTestimonial {
	author: string;
	testimonial: StoryblokRichtext;
	component: 'ProjectTestimonial';
	_uid: string;
}

export interface StoryblokQuotes {
	quotes?: StoryblokQuotesItem[];
	cursorProjects?: boolean;
	circularStar?: boolean;
	component: 'Quotes';
	_uid: string;
}

export interface StoryblokQuotesItem {
	content: StoryblokRichtext;
	component: 'QuotesItem';
	_uid: string;
}

export interface StoryblokSEO {
	title: string;
	description: string;
	og_title?: string;
	og_description?: string;
	og_image?: StoryblokAsset;
	keywords?: string;
	component: 'SEO';
	_uid: string;
}

export interface StoryblokService {
	SEO: StoryblokSEO[];
	informations: StoryblokServiceInformations[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Service';
	_uid: string;
}

export interface StoryblokServiceFAQ {
	title: StoryblokRichtext;
	description: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	sections?: StoryblokServiceFAQSection[];
	component: 'ServiceFAQ';
	_uid: string;
}

export interface StoryblokServiceFAQSection {
	title: string;
	questions?: StoryblokServiceFAQSectionItem[];
	component: 'ServiceFAQSection';
	_uid: string;
}

export interface StoryblokServiceFAQSectionItem {
	question: string;
	answer: StoryblokRichtext;
	component: 'ServiceFAQSectionItem';
	_uid: string;
}

export interface StoryblokServiceInformations {
	name: StoryblokRichtext;
	summary: string;
	cover: StoryblokAsset;
	component: 'ServiceInformations';
	_uid: string;
}

export interface StoryblokServices {
	SEO: StoryblokSEO[];
	body?: (
		| StoryblokBiographyCopyright
		| StoryblokBiographyHero
		| StoryblokBiographyStrangersPortraits
		| StoryblokHomeHero
		| StoryblokLinksHero
		| StoryblokLinksMaterials
		| StoryblokOtherServices
		| StoryblokProjectsMarquee
		| StoryblokProjectTestimonial
		| StoryblokQuotes
		| StoryblokServiceFAQ
		| StoryblokServicesHero
		| StoryblokServicesHighlight
		| StoryblokServicesItem
		| StoryblokServiceTestimonials
		| StoryblokSteps
	)[];
	component: 'Services';
	_uid: string;
}

export interface StoryblokServicesHero {
	title: StoryblokRichtext;
	subtitle: string;
	description: string;
	component: 'ServicesHero';
	_uid: string;
}

export interface StoryblokServicesHighlight {
	service: (ISbStoryData<StoryblokService> | string)[];
	project: (ISbStoryData<StoryblokProject> | string)[];
	component: 'ServicesHighlight';
	_uid: string;
}

export interface StoryblokServicesItem {
	service: (ISbStoryData<StoryblokService> | string)[];
	projects: (ISbStoryData<StoryblokProject> | string)[];
	isReversed?: boolean;
	component: 'ServicesItem';
	_uid: string;
}

export interface StoryblokServiceTestimonials {
	title: string;
	description: string;
	link?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	testimonials?: StoryblokServiceTestimonialsItem[];
	component: 'ServiceTestimonials';
	_uid: string;
}

export interface StoryblokServiceTestimonialsItem {
	author: string;
	testimonial: StoryblokRichtext;
	pictures?: StoryblokServiceTestimonialsItemPicture[];
	component: 'ServiceTestimonialsItem';
	_uid: string;
}

export interface StoryblokServiceTestimonialsItemPicture {
	picture: StoryblokAsset;
	component: 'ServiceTestimonialsItemPicture';
	_uid: string;
}

export interface StoryblokSiteConfig {
	titleContact: string;
	descriptionContact: string;
	identity: string;
	email: string;
	socials: StoryblokLabelLink[];
	menuDescription: string;
	menuLinks?: StoryblokLabelLink[];
	titleTemplate: string;
	defaultTitle: string;
	defaultDescription: string;
	defaultImage: StoryblokAsset;
	favicon: StoryblokAsset;
	formsContact: (ISbStoryData<StoryblokForms> | string)[];
	component: 'SiteConfig';
	_uid: string;
}

export interface StoryblokSteps {
	steps?: StoryblokStepsItem[];
	circularStar?: boolean;
	component: 'Steps';
	_uid: string;
}

export interface StoryblokStepsItem {
	title: string;
	description: string;
	cta?: StoryblokLabelLink[];
	component: 'StepsItem';
	_uid: string;
}

export interface StoryblokTitleDescriptionAndCta {
	title: StoryblokRichtext;
	description: string;
	cta?: StoryblokLabelLink[];
	component: 'TitleDescriptionAndCta';
	_uid: string;
}

export type ContentType =
	| StoryblokBiography
	| StoryblokForms
	| StoryblokHome
	| StoryblokLinks
	| StoryblokMenu
	| StoryblokProject
	| StoryblokService
	| StoryblokServices
	| StoryblokSiteConfig;

type StoryblokPropertyType = 'asset' | 'multiasset' | 'multilink' | 'table' | 'richtext';

interface StoryblokAsset {
	poster?: StoryblokAsset | string | null;
	vimeoId?: string;
	assetType?: 'video' | null;
	alt: string | null;
	copyright: string | null;
	fieldtype: 'asset';
	id: number;
	filename: string | null;
	name: string;
	title: string | null;
	focus: string | null;
	meta_data: Record<string, any>;
	source: string | null;
	is_external_url: boolean;
	is_private: boolean;
	src: string;
	updated_at: string;
	width: number | null;
	height: number | null;
	aspect_ratio: number | null;
	public_id: string | null;
	content_type: string;
}

interface StoryblokMultiasset extends Array<StoryblokAsset> {}

interface StoryblokMultilinkStory {
	name: string;
	created_at: string;
	published_at: string;
	id: number;
	uuid: string;
	content: Record<string, any>;
	slug: string;
	full_slug: string;
	sort_by_date?: string;
	position?: number;
	tag_list?: string[];
	is_startpage?: boolean;
	parent_id?: number | null;
	meta_data?: Record<string, any> | null;
	group_id?: string;
	first_published_at?: string;
	release_id?: number | null;
	lang?: string;
	path?: string | null;
	alternates?: any[];
	default_full_slug?: string | null;
	translated_slugs?: any[] | null;
}

interface StoryblokMultilinkLink {
	id: number;
	uuid: string;
	slug: string;
	path: string | null;
	parent_id: number;
	name: string;
	is_folder: boolean;
	published: boolean;
	is_startpage: boolean;
	position: number;
	real_path: string;
}

interface StoryblokMultilinkUrl {
	name: string;
	id: number;
	uuid: string;
	slug: string;
	url: string;
	full_slug: string;
}

interface StoryblokMultilink {
	name?: string;
	component?: string;
	fieldtype: 'multilink';
	id: string;
	url: string;
	cached_url: string;
	target?: '_blank' | '_self';
	anchor?: string;
	rel?: string;
	title?: string;
	prep?: string;
	linktype: 'story' | 'url' | 'email' | 'asset';
	story?: StoryblokMultilinkStory | StoryblokMultilinkLink | StoryblokMultilinkUrl;
	email?: string;
}

interface StoryblokTable {
	fieldtype: 'table';
	thead: Array<{
		_uid: string;
		value: string;
		component: '_table_head';
		_editable?: string;
	}>;
	tbody: Array<{
		_uid: string;
		component: '_table_row';
		_editable?: string;
		body: Array<{
			_uid: string;
			value: string;
			component: '_table_col';
			_editable?: string;
		}>;
	}>;
}

interface StoryblokRichtext {
	type: string;
	content?: StoryblokRichtext[];
	marks?: StoryblokRichtext[];
	attrs?: Record<string, any>;
	text?: string;
}
