import type { Event, Product } from '#types/externals.ts';

// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.

export interface StoryblokBiography {
	SEO: StoryblokSEO[];
	component: 'Biography';
	_uid: string;
}

export interface StoryblokEmail {
	label: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'asset' }>;
	component: 'Email';
	_uid: string;
}

export interface StoryblokForms {
	title: string;
	description: string;
	inputs?: (StoryblokInputEmail | StoryblokInputRadios | StoryblokInputText | StoryblokInputTextarea)[];
	formsSuccess?: StoryblokFormsSuccess[];
	formsError?: StoryblokFormsError[];
	component: 'Forms';
	_uid: string;
}

export interface StoryblokFormsError {
	title: string;
	subtitle: string;
	description: string;
	component: 'FormsError';
	_uid: string;
}

export interface StoryblokFormsSuccess {
	title: string;
	subtitle: string;
	description: string;
	component: 'FormsSuccess';
	_uid: string;
}

export interface StoryblokHome {
	SEO: StoryblokSEO[];
	component: 'Home';
	_uid: string;
}

export interface StoryblokInputEmail {
	label: string;
	placeholder: string;
	component: 'InputEmail';
	_uid: string;
}

export interface StoryblokInputRadios {
	label: string;
	placeholder: string;
	component: 'InputRadios';
	_uid: string;
}

export interface StoryblokInputText {
	label: string;
	placeholder: string;
	component: 'InputText';
	_uid: string;
}

export interface StoryblokInputTextarea {
	label: string;
	placeholder: string;
	component: 'InputTextarea';
	_uid: string;
}

export interface StoryblokLabelLink {
	label: string;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	component: 'LabelLink';
	_uid: string;
}

export interface StoryblokLinks {
	SEO: StoryblokSEO[];
	component: 'Links';
	_uid: string;
}

export interface StoryblokMenu {
	title: string;
	description: string;
	navLinks?: StoryblokLabelLink[];
	component: 'Menu';
	_uid: string;
}

export interface StoryblokPicture {
	media: StoryblokAsset;
	component: 'Picture';
	_uid: string;
}

export interface StoryblokProject {
	SEO: StoryblokSEO[];
	component: 'Project';
	_uid: string;
}

export interface StoryblokSEO {
	title: string;
	description: string;
	og_title?: string;
	og_description?: string;
	og_image?: StoryblokAsset;
	keywords?: string;
	component: 'SEO';
	_uid: string;
}

export interface StoryblokService {
	SEO: StoryblokSEO[];
	component: 'Service';
	_uid: string;
}

export interface StoryblokServices {
	SEO: StoryblokSEO[];
	component: 'Services';
	_uid: string;
}

export interface StoryblokSiteConfig {
	menuDescription: string;
	menuLinks?: StoryblokLabelLink[];
	identity: string;
	email: StoryblokEmail[];
	socials: StoryblokLabelLink[];
	titleTemplate: string;
	defaultTitle: string;
	defaultDescription: string;
	defaultImage: StoryblokAsset;
	favicon: StoryblokAsset;
	component: 'SiteConfig';
	_uid: string;
}

export type ContentType =
	| StoryblokBiography
	| StoryblokForms
	| StoryblokHome
	| StoryblokLinks
	| StoryblokMenu
	| StoryblokProject
	| StoryblokService
	| StoryblokServices
	| StoryblokSiteConfig;

type StoryblokPropertyType = 'asset' | 'multiasset' | 'multilink' | 'table' | 'richtext';

interface StoryblokAsset {
	poster?: StoryblokAsset | string | null;
	vimeoId?: string;
	assetType?: 'video' | null;
	alt: string | null;
	copyright: string | null;
	fieldtype: 'asset';
	id: number;
	filename: string | null;
	name: string;
	title: string | null;
	focus: string | null;
	meta_data: Record<string, any>;
	source: string | null;
	is_external_url: boolean;
	is_private: boolean;
	src: string;
	updated_at: string;
	width: number | null;
	height: number | null;
	aspect_ratio: number | null;
	public_id: string | null;
	content_type: string;
}

interface StoryblokMultiasset extends Array<StoryblokAsset> {}

interface StoryblokMultilinkStory {
	name: string;
	created_at: string;
	published_at: string;
	id: number;
	uuid: string;
	content: Record<string, any>;
	slug: string;
	full_slug: string;
	sort_by_date?: string;
	position?: number;
	tag_list?: string[];
	is_startpage?: boolean;
	parent_id?: number | null;
	meta_data?: Record<string, any> | null;
	group_id?: string;
	first_published_at?: string;
	release_id?: number | null;
	lang?: string;
	path?: string | null;
	alternates?: any[];
	default_full_slug?: string | null;
	translated_slugs?: any[] | null;
}

interface StoryblokMultilinkLink {
	id: number;
	uuid: string;
	slug: string;
	path: string | null;
	parent_id: number;
	name: string;
	is_folder: boolean;
	published: boolean;
	is_startpage: boolean;
	position: number;
	real_path: string;
}

interface StoryblokMultilinkUrl {
	name: string;
	id: number;
	uuid: string;
	slug: string;
	url: string;
	full_slug: string;
}

interface StoryblokMultilink {
	name?: string;
	component?: string;
	fieldtype: 'multilink';
	id: string;
	url: string;
	cached_url: string;
	target?: '_blank' | '_self';
	anchor?: string;
	rel?: string;
	title?: string;
	prep?: string;
	linktype: 'story' | 'url' | 'email' | 'asset';
	story?: StoryblokMultilinkStory | StoryblokMultilinkLink | StoryblokMultilinkUrl;
	email?: string;
}

interface StoryblokTable {
	fieldtype: 'table';
	thead: Array<{
		_uid: string;
		value: string;
		component: '_table_head';
		_editable?: string;
	}>;
	tbody: Array<{
		_uid: string;
		component: '_table_row';
		_editable?: string;
		body: Array<{
			_uid: string;
			value: string;
			component: '_table_col';
			_editable?: string;
		}>;
	}>;
}

interface StoryblokRichtext {
	type: string;
	content?: StoryblokRichtext[];
	marks?: StoryblokRichtext[];
	attrs?: Record<string, any>;
	text?: string;
}
