name: Deploy (Preprod & Production)

on:
  push:
    branches:
      - env/preprod
      - env/production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # 🔵 PREPROD :
      - name: Deploy to Preprod
        if: github.ref_name == 'env/preprod'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /public_html/preprod/
          dangerous-clean-slate: true

      # 🟢 PROD :
      - name: Deploy to Production
        if: github.ref_name == 'env/production'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /public_html/
          dangerous-clean-slate: true
